@startuml class

skin rose

title Classes - Class Diagram


abstract class PizzaStore {
  {abstract} CheesePizza createCheesePizza()
  {abstract} VeganPizza createVeganPizza()
  {abstract} HawaiianPizza createHawaiianPizza()
  
  Pizza orderPizza(String request)
  
}

PizzaStore ..> Pizza

class NYPizzaFactory extends PizzaStore {
  CheesePizza createCheesePizza()
  VeganPizza createVeganPizza()
  HawaiianPizza createHawaiianPizza()
}

class ChicagoPizzaFactory extends PizzaStore {
  CheesePizza createCheesePizza()
  VeganPizza createVeganPizza()
  HawaiianPizza createHawaiianPizza()
}

class CaliforniaPizzaFactory extends PizzaStore {
  CheesePizza createCheesePizza()
  VeganPizza createVeganPizza()
  HawaiianPizza createHawaiianPizza()
}

interface Pizza {
  void prepare()
}

class CheesePizza implements Pizza {
  void prepare()
}
class VeganPizza implements Pizza {
  void prepare()
}
class HawaiianPizza implements Pizza {
  void prepare()
}

@enduml